version: '3'
services:
  redis:
    image: redis/redis-stack:latest
    container_name: siph-asr-redis
    ports:
      - '6379:6379'
      - '8001:8001'
    restart: always
    env_file:
      - ./.env
    volumes:
      - redis-db-siph-asr:/data
volumes:
  redis-db-siph-asr: